name: Build and Release Matchio

on:
  pull_request:
    types: [closed]
    branches:
      - master

jobs:
  build-and-release:
    if: github.event.pull_request.merged == true
    runs-on: windows-latest # Use Windows since you're building a Windows exe

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install -r requirements.txt  # if you have one

      - name: Build Matchio executable
        run: |
          pyinstaller src/main.py --onefile --windowed --name=Matchio --icon=icon/finished-icon.ico

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ github.run_number }}
          name: Release v${{ github.run_number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}

      - name: Upload Matchio.exe to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/Matchio.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
